### ISSUE TITLE
Error with main.lua - nil has a symbol

### ISSUE THREAD

**Issue by jojomoore2007** [oeed/Silica#25]
# OK, here's the problem:

If you look at line 117 of main.lua, you find the following:
```lua
if _conf.compat_loadstringMask ~= Ïnil then
```
Hold on, though, what's that `Ï` symbol doing there?
That's the issue.
The line *should* have:
```lua
if _conf.compat_loadstringMask ~= nil then
```
...but it doesn't. This is a big error and turns everything around. PLZ FIX!!!!!

**Comment by exerro** [comment]
Can you link to the file this is in? I couldn't find it [in a search](https://github.com/oeed/Silica/search?q=compat_loadstringMask&unscoped_q=compat_loadstringMask).

Btw, if you ctick on the line when viewing a file it'll update the URL to highlight that line.

**Comment by oeed** [comment]
While Silica is one of the things I am most proud of working on, I'm afraid its pretty much dead. Maybe one day years from now it'll be resurrected, or maybe I'll try get it at least working, but certainly not any time soon.
