### ISSUE TITLE
Weird graphic when "pushing out" characters(tried with H)

### ISSUE THREAD

**Issue by Luca0208** [oeed/Silica#7]
If you enter a H in a textbox and then push it out with some character(Probably works with other characters than H) it will show a dot at the border of the text box.

Demo vid: https://www.youtube.com/watch?v=3duldMh7Ci8&feature=youtu.be

**Comment by oeed** [comment]
Oh hadn't seen that before, thanks!

**Comment by oeed** [comment]
Fixed in oeed/Silica@70f9092 (new-graphics-system), thanks!
